name: Feature Request
description: Request a new feature
title: "[feature]: "
labels: ["feature", "request"]
assignees:
  - Ross Power
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-info
    attributes:
      label: What is the feature you'd like to see?
      description: Also tell us, what you were doing that prompted this idea?
      placeholder: Let's hear your idea!
      value: "I'd love to see...!"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link for context
      description: Please provide a link of where any other projects (ideally on Cosmos) that use this feature, for better context.
      placeholder: https://github.com/cheqd/cheqd-node
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cheqd/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
