name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:

  staging-deploy:
    name: "Cloudflare - Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://validator-status-staging.cheqd.net/

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.25'
          preCommands: npm ci
          command: publish --env staging
          secrets: ZAPIER_URL
        env:
          ZAPIER_URL: ${{ secrets.WEBHOOK_URL }}

  production-deploy:
    name: "Cloudflare - Production"
    needs: staging-deploy
    if: ${{ success() && ( github.ref_name == 'main' ) }}
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    environment:
      name: production
      url: https://validator-status.cheqd.net/
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.25'
          preCommands: npm ci
          command: publish
          secrets: ZAPIER_URL
        env:
          ZAPIER_URL: ${{ secrets.WEBHOOK_URL }}
