name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:

  staging-deploy:
    name: "Cloudflare - Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://validator-status-staging.cheqd.net/

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3.3.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.29'
          environment: "staging"
          preCommands: npm ci
          command: publish --env staging
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.ZAPIER_URL }}

  production-deploy:
    name: "Cloudflare - Production"
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://validator-status.cheqd.net/
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3.3.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.29'
          preCommands: npm ci
          # `publish` goes to production by default
          command: publish
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.ZAPIER_URL }}
